version: '3'

services:
  db:
    container_name: db_books_test
    image: postgres:16.2-alpine3.19
    restart: always
    env_file:
      - .development.env
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  backend_books:
    container_name: backend_books
    build:
     context: .
    env_file:
      - .development.env
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - db
    restart: always